### ISSUE TITLE
QA for Maze menu

### ISSUE THREAD

**Issue by tanjunwu** [ktzy0305/MazeGame#13]
When the program is run, it should display the main menu.
When a user enters an option from 0 to 4, the program will process the option
accordingly. After the option has been processed, the program will display the
main menu again and the process is repeated until the user chooses to exit.

Main menu
1. Read and load maze from file
2. View maze
3. Play maze game
4. Configure current maze
0. Exit Maze

**Comment by githubbing97** [comment]
ok. done.

**Comment by ktzy0305** [comment]
Thanks! @githubbing97
