### ISSUE TITLE
(QA) File not found for the "test_QApytest_mainmenu.py"

### ISSUE THREAD

**Issue by githubbing97** [ktzy0305/MazeGame#16]
I'll put the "test_QApytest_mainmenu.py" outside of QA folder because it does not run when it is inside a directory.

**Comment by ktzy0305** [comment]
@githubbing97 
Try add these lines of code to every QA test file

```
import os, sys
sys.path.append(os.getcwd())
sys.path.append("..")
```

**Comment by githubbing97** [comment]
@ktzy0305  it works already ! thanks kevin !
