### ISSUE TITLE
(QA) python pytest unable to do automated user interface testing

### ISSUE THREAD

**Issue by githubbing97** [ktzy0305/MazeGame#17]
I've tried many ways to find the python Pytest online for automated user interface testing but didn't make it.  Most of the solution does not work for me, there is some solutions but I do not really understand how to apply to my QA user interface testing.

**Comment by ktzy0305** [comment]
@githubbing97 Its alright, we will just stick will manual acceptance testing then, remember to make records that you have completed the testing as evidence
