### ISSUE TITLE
[Bug] Build gets stuck when running "pytest -sv --cov" in Docker

### ISSUE THREAD

**Issue by ktzy0305** [ktzy0305/MazeGame#19]
![image](https://user-images.githubusercontent.com/36191443/73603373-92f63a80-45bc-11ea-85f9-a2a8f68a19d5.png)
As you can see, the unit test for test_option_1 requires an input and we need to figure out a way to bypass that

**Comment by tanjunwu** [comment]
@ktzy0305  issue solved. Skipped the input() after entering and checking of option for the menu. When running pytest, prompting should occur anymore.
