### ISSUE TITLE
(QA) Manual acceptance test done for mainmenu function and read and load datafile. 

### ISSUE THREAD

**Issue by githubbing97** [ktzy0305/MazeGame#20]
I've added those screenshots in my QA folder. may take a look, thanks! 

In addition, I've also added option 5 (configure current maze) test cases in the word document. 
@ktzy0305 @tanjunwu

**Comment by ktzy0305** [comment]
@githubbing97 Noted with thanks, I will take a look at them

**Comment by ktzy0305** [comment]
@githubbing97 I have checked them, and verified your screenshots with each test and all of them for these 2 functions have passed. Great job, keep it up.
