### ISSUE TITLE
[OS Compatibility] Tests passed in Windows but fails in ShiningPanda and Docker

### ISSUE THREAD

**Issue by ktzy0305** [ktzy0305/MazeGame#22]
The docker and shining panda in Jenkins is running on Linux, which its file system is case sensitive. The unit test "**test_filename_case_sensitive test case**"  passed in Windows but in Shining Panda and Docker it has failed. So we have to remove the test_filename_case_sensitive test case. And that the for test_filenameinput, you need to change check_filename("maze.csv") to check_filename("Maze.csv")

![image](https://user-images.githubusercontent.com/36191443/73949925-0b9b2500-4936-11ea-855f-430ebeaf1393.png)

**Comment by Klann98** [comment]
The docker and shining panda in Jenkins is running on Linux its file system is case sensitive. The unit test passed in Windows but in Shining Panda and Docker it failed. So I removed the test_filename_case_sensitive test case. And that the for test_filenameinput, I changed check_filename("maze.csv") to check_filename("Maze.csv")
Commit: 37004da
@ktzy0305

**Comment by ktzy0305** [comment]
Thanks @Klann98
