### ISSUE TITLE
QA for Play maze game

### ISSUE THREAD

**Issue by tanjunwu** [ktzy0305/MazeGame#3]
This option allows the user to play the maze game. It **displays the maze** from
the list created, the start and end location as was done in another feature and the user
**can enter** one of the following characters: **W,A,S,D or M** for **moving UP, LEFT,
DOWN, RIGHT or MAIN MENU** respectively, the program will **process the
option accordingly if it is a valid option.**
Display invalid message if move is invalid (wrong imputation, got walls blocking moving direction), else process and update the location of "A"(MOVE IT).

**Comment by githubbing97** [comment]
ok done @ktzy0305
