### ISSUE TITLE
QA for Configure current maze

### ISSUE THREAD

**Issue by tanjunwu** [ktzy0305/MazeGame#4]
This feature allows the user to change the configuration of the current maze by
changing some of the walls and paths, the start and end locations. The sample
outputs show one way this can be done. **You are free to design your method
for configuring the maze.**
(Just don't increase the maze size)--> not sure with this yet will confirm and update

**Comment by githubbing97** [comment]
@ktzy0305  ok done .

**Comment by ktzy0305** [comment]
Thanks @githubbing97
