### ISSUE TITLE
Read and load maze from file

### ISSUE THREAD

**Issue by tanjunwu** [ktzy0305/MazeGame#5]
This feature allows the user to read the maze diagram from the data file
and store it in memory. It also stores the start (A) location and the end (B)
location. The application should prompt the user for the name of the data file.

**Comment by Klann98** [comment]
created pytest  for the read and load feature for option 1
Commit: d2508eb @ktzy0305

**Comment by Klann98** [comment]
Option 1 "Read and Load maze" , application is able to read and load the maze.csv file and print the right amount of lines. But pytest fails, errors showing 
@ktzy0305
QA can start testing @githubbing97  
Commit: eec9c3d

**Comment by Klann98** [comment]
@ktzy0305 @tanjunwu try helping resolving pytest issue. Pytest no open csv file function.

**Comment by tanjunwu** [comment]
@Klann98 issue solved
