### ISSUE TITLE
View maze

### ISSUE THREAD

**Issue by tanjunwu** [ktzy0305/MazeGame#6]
This feature allows the user to view the stored maze from the memory (in list format), done in another feature. The code for this option should not read the maze from the data file again but instead from the stored memory

**Comment by kealtke** [comment]
Finished the python test script and implemented option 2 (view maze) afterwards. I have also updated the test case document with 1 additional test case

Commit 62dda33

@ktzy0305

**Comment by kealtke** [comment]
@githubbing97 QA can start testing
