### ISSUE TITLE
Configure current maze

### ISSUE THREAD

**Issue by tanjunwu** [ktzy0305/MazeGame#8]
This feature allows the user to change the configuration of the current maze by
changing some of the walls and paths, the start and end locations. The sample
outputs show one way this can be done. You are free to design your method
for configuring the maze.
(Just don't increase the maze size)--> not sure with this yet will confirm and update

**Comment by ktzy0305** [comment]
@tanjunwu I have written the developer test cases for the configure current maze feature as well as done the unit tests for it before coding the actual thing. It can be found at commit 8978674

**Comment by ktzy0305** [comment]
@tanjunwu I have completed the feature for Configure Maze and passed the unit tests at commit 795516c. QA @githubbing97 can start the testing

**Comment by tanjunwu** [comment]
@ktzy0305 great job
